# Generated by Django 4.2.16 on 2026-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web App'), ('3d', '3D / WebGL'), ('game', 'Game Dev'), ('other', 'Other')], default='web', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('demo_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('accent_color', models.CharField(default='#a855f7', max_length=20)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('creative', 'Creative'), ('tools', 'Tools')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=80, help_text='0-100')),
                ('color', models.CharField(default='#a855f7', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
